export const NATIONAL_NEWS_SOURCES = [
  {
    id: "ndtv",
    name: "NDTV",
    category: "National",
    href: "https://www.ndtv.com/india",
    description: "National coverage and breaking election stories from a major Indian newsroom.",
  },
  {
    id: "times-now",
    name: "Times Now",
    category: "National",
    href: "https://www.timesnownews.com/india",
    description: "Fast-moving political coverage and election live blogs.",
  },
  {
    id: "cnn-news18",
    name: "CNN-News18",
    category: "National",
    href: "https://www.news18.com/politics/",
    description: "National politics, campaign updates, and election explainers.",
  },
  {
    id: "india-today",
    name: "India Today",
    category: "National",
    href: "https://www.indiatoday.in/elections",
    description: "Election news, interviews, and state-by-state coverage.",
  },
];

export const TAMIL_NADU_NEWS_SOURCES = [
  {
    id: "puthiyathalaimurai",
    name: "Puthiya Thalaimurai",
    category: "Tamil Nadu",
    href: "https://www.puthiyathalaimurai.com/topic/2026-tamil-nadu-election",
    description: "Dedicated Tamil Nadu election topic page with regional political coverage and rolling updates.",
    badge: "Featured",
  },
  {
    id: "daily-thanthi",
    name: "Daily Thanthi Election",
    category: "Tamil Nadu",
    href: "https://election.dailythanthi.com/",
    description: "Election-focused coverage from one of Tamil Nadu's biggest news brands.",
    badge: "Featured",
  },
  {
    id: "oneindia-tamil",
    name: "Oneindia Tamil Elections",
    category: "Tamil Nadu",
    href: "https://tamil.oneindia.com/tamil-nadu-assembly-elections/",
    description: "Tamil Nadu assembly election coverage with constituency and campaign stories.",
    badge: "Featured",
  },
  {
    id: "news18-tamil",
    name: "News18 Tamil Nadu",
    category: "Tamil Nadu",
    href: "https://tamil.news18.com/",
    description: "Tamil breaking news and election updates from News18's regional desk.",
    badge: "Featured",
  },
  {
    id: "thanthi-tv",
    name: "Thanthi TV",
    category: "Tamil Nadu",
    href: "https://www.thanthitv.com/",
    description: "Regional TV newsroom with strong election-day and constituency coverage.",
  },
  {
    id: "sun-news",
    name: "Sun News",
    category: "Tamil Nadu",
    href: "https://www.sunnewslive.in/",
    description: "Tamil live news coverage and state politics updates.",
  },
  {
    id: "news7-tamil",
    name: "News7 Tamil",
    category: "Tamil Nadu",
    href: "https://www.news7tamil.live/",
    description: "Tamil Nadu political updates, interviews, and local campaign coverage.",
  },
  {
    id: "polimer-news",
    name: "Polimer News",
    category: "Tamil Nadu",
    href: "https://polimernews.com/",
    description: "Regional breaking news feed with Tamil Nadu political coverage.",
  },
];
